require_relative 'blog/db_adapter'
require_relative 'blog/post_manager'
require_relative 'blog/post_form'
require 'sinatra'
require 'sinatra/activerecord'
require_relative '../config/enviroments'
require_relative '../models/post'
