development:
  adapter: postgresql
  encoding: unicode
  database: ODQ_APP
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ODQ_APP
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ODQ_APP_test
  pool: 5
